gText_Birch_Welcome::
	.string "Hi! You installed this correctly!\p"
	.string "Welcome to the Semi-Randomiser!\p"
	.string "This guy is BIRCH. But I'm Anguish.\p"
	.string "This romhack randomises all enemy\n"
	.string "trainer POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Like this one, here:”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Haha! Look at my cool LOTAD.\n"
	.string "This algorithm is a real menace.\p"
	.string "I don't know what you'll find,\n"
	.string "but this was designed to be played\l"
	.string "blind in a nuzlocke setting.\p"
	.string "Most stuff is vanilla, but shops\n"
	.string "stock candies and cheaper balls.\p"
	.string "Also, GYM statues will tell you\n"
	.string "level caps, if you forget.\p"
	.string "That's all from me for now!\n"
	.string "Good luck!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Do you want to play as the boy?\n"
	.string "Or play as the girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
